# DelGuard 测试配置文件 (YAML格式)
basic:
  version: "1.0.0"
  language: "zh-cn"
  log_level: "info"
  interactive_mode: "auto"
  safe_mode: "enabled"

performance:
  show_progress: true
  batch_size: 100
  parallel: true
  max_workers: 4

ui:
  color_output: true
  show_stats: true
  notifications: true
  progress_style: "bar"