# DelGuard Suomenkielinen kielipaketti
# TOML-muoto jäsennellyillä osioilla
# Versio: 1.0.0

[basic_operations]
"DelGuard - 跨平台安全删除工具" = "DelGuard - Alustojen Välinen Turvallinen Poistotyökalu"
"用法:" = "Käyttö:"
"选项:" = "Vaihtoehdot:"
"文件:" = "Tiedosto:"
"目录:" = "Hakemisto:"
"版本" = "Versio"
"帮助" = "Ohje"

[deletion_operations]
"删除 %s ? [y/N/a/q]: " = "Poista %s ? [y/N/a/q]: "
"已跳过 %s\n" = "Ohitettiin %s\n"
"检测到关键路径，要求双重确认：%s\n" = "Kriittinen polku havaittu, kaksinkertainen vahvistus vaaditaan: %s\n"
"已取消关键路径 %s 的删除\n" = "Kriittisen polun %s poisto peruutettu\n"
"[DRY-RUN] 将把 %s 移动到回收站\n" = "[KUIVA-AJO] Siirtäisi %s roskakoriin\n"
"错误：无法删除 %s: %v\n" = "Virhe: ei voida poistaa %s: %v\n"
"已将 %s 移动到回收站\n" = "Siirrettiin %s roskakoriin\n"

[system_warnings]
"警告：当前以高权限运行（root/管理员），已强制启用交互确认。\n" = "Varoitus: käynnissä korkeilla oikeuksilla (root/Järjestelmänvalvoja). Interaktiivinen vahvistus pakotettu.\n"
"当前平台 %s 暂不支持回收站功能\n" = "Nykyinen alusta %s ei tue roskakorin toiminnallisuutta\n"
"警告：即将删除关键路径: %s\n" = "Varoitus: aikeissa poistaa kriittinen polku: %s\n"
"为确认风险，请输入完整路径继续（或直接回车取消）：" = "Riskin vahvistamiseksi, syötä koko polku jatkaaksesi (tai paina Enter peruuttaaksesi): "
"警告：当前以管理员/root权限运行，即将删除: %s\n" = "Varoitus: käynnissä järjestelmänvalvojana/root, aikeissa poistaa: %s\n"
"确认删除？[y/N]: " = "Vahvista poisto? [y/N]: "

[file_status]
"警告：文件 %s 为只读文件\n" = "Varoitus: tiedosto %s on kirjoitussuojattu\n"
"确认删除只读文件？[y/N]: " = "Vahvista kirjoitussuojatun tiedoston poisto? [y/N]: "
"警告：检测到回收站/废纸篓目录: %s\n" = "Varoitus: roskakori/paperikori hakemisto havaittu: %s\n"
"确认删除回收站目录？[y/N]: " = "Vahvista roskakorihakemiston poisto? [y/N]: "
"警告：检测到DelGuard程序目录: %s\n" = "Varoitus: DelGuard ohjelma hakemisto havaittu: %s\n"
"确认删除程序目录？[y/N]: " = "Vahvista ohjelma hakemiston poisto? [y/N]: "

[error_messages]
"错误：权限不足，无法删除 %s\n" = "Virhe: riittämättömät oikeudet poistaa %s\n"
"错误：系统保护文件，无法删除 %s\n" = "Virhe: järjestelmän suojattu tiedosto, ei voida poistaa %s\n"
"错误：路径包含非法字符: %s\n" = "Virhe: polku sisältää virheellisiä merkkejä: %s\n"
"错误：路径过长: %s\n" = "Virhe: polku liian pitkä: %s\n"
"错误：磁盘空间不足，无法删除 %s\n" = "Virhe: riittämätön levytila poistaa %s\n"
"错误：文件正在被使用: %s\n" = "Virhe: tiedosto on käytössä: %s\n"
"错误：网络路径不可访问: %s\n" = "Virhe: verkko polku ei saavutettavissa: %s\n"
"错误：符号链接目标不存在: %s\n" = "Virhe: symbolisen linkin kohde ei ole olemassa: %s\n"
"错误：文件系统只读: %s\n" = "Virhe: tiedostojärjestelmä on kirjoitussuojattu: %s\n"
"错误：磁盘错误: %s\n" = "Virhe: levyvirhe: %s\n"
"错误：内存不足: %s\n" = "Virhe: riittämätön muisti: %s\n"

[smart_search]
"未找到文件 '%s'，但发现以下相似文件：" = "Tiedostoa '%s' ei löytynyt, mutta samankaltaisia tiedostoja löytyi:"
"请选择文件编号" = "Valitse tiedostonumero"
"取消操作" = "Peruuta toiminto"
"选择了文件" = "Tiedosto valittu"
"相似度" = "Samankaltaisuus"
"匹配方式" = "Täsmäämistyyppi"
"内容匹配" = "Sisältötäsmäys"

[user_interface]
"确认" = "Vahvista"
"取消" = "Peruuta"
"跳过" = "Ohita"
"全部" = "Kaikki"
"退出" = "Poistu"
"继续" = "Jatka"
"重试" = "Yritä uudelleen"
"忽略" = "Ohita"

[progress_stats]
"删除进度" = "Poiston edistyminen"
"完成" = "Valmis"
"失败" = "Epäonnistui"
"成功" = "Onnistui"
"总计" = "Yhteensä"
"处理中" = "Käsitellään"
"已完成" = "Valmistunut"

[configuration]
"配置" = "Konfiguraatio"
"设置" = "Asetukset"
"语言" = "Kieli"
"主题" = "Teema"
"日志" = "Loki"
"备份" = "Varmuuskopio"
"安全" = "Turvallisuus"
"性能" = "Suorituskyky"

[help_info]
"使用帮助" = "Käyttöohje"
"命令说明" = "Komennon kuvaus"
"参数列表" = "Parametriluettelo"
"示例" = "Esimerkit"
"注意事项" = "Huomioitavaa"
"常见问题" = "Usein kysytyt kysymykset"

[file_types]
"文件" = "Tiedosto"
"目录" = "Hakemisto"
"符号链接" = "Symbolinen linkki"
"隐藏文件" = "Piilotettu tiedosto"
"系统文件" = "Järjestelmätiedosto"
"只读文件" = "Kirjoitussuojattu tiedosto"
"可执行文件" = "Suoritettava tiedosto"

[operation_results]
"操作成功" = "Toiminto onnistui"
"操作失败" = "Toiminto epäonnistui"
"操作取消" = "Toiminto peruutettu"
"操作超时" = "Toiminto aikakatkaistiin"
"操作完成" = "Toiminto valmis"
"操作中断" = "Toiminto keskeytetty"

[special_features]
"智能搜索" = "Älykäs haku"
"自动备份" = "Automaattinen varmuuskopio"
"安全删除" = "Turvallinen poisto"
"批量处理" = "Eräkäsittely"
"并行处理" = "Rinnakkaiskäsittely"
"增量备份" = "Inkrementaalinen varmuuskopio"

# Kehittyneet ominaisuudet
[advanced_features]
"高级配置" = "Kehittynyt konfiguraatio"
"性能优化" = "Suorituskyvyn optimointi"
"安全增强" = "Turvallisuuden parantaminen"
"用户体验" = "Käyttäjäkokemus"
"自定义选项" = "Mukautetut vaihtoehdot"
"扩展功能" = "Laajennetut toiminnot"

# Uudet ominaisuudet
[new_features]
"并行处理支持" = "Rinnakkaiskäsittelyn tuki"
"智能备份策略" = "Älykäs varmuuskopiointistrategia"
"高级过滤器" = "Kehittyneet suodattimet"
"用户钩子系统" = "Käyttäjän hook-järjestelmä"
"配置文件格式" = "Konfiguraatiotiedoston muodot"
"多语言支持" = "Monikielinen tuki"

# Käyttäjämukautetut asetukset
[custom_settings]
"主题设置" = "Teeman asetukset"
"界面布局" = "Käyttöliittymän asettelu"
"快捷键" = "Pikanäppäimet"
"通知设置" = "Ilmoitusasetukset"
"日志记录" = "Lokin tallennus"
"缓存管理" = "Välimuistin hallinta"
