# DelGuard Svenska språkpaket
# YAML-format med strukturerat stöd
# Version: 1.0.0

basic_operations:
  "DelGuard - 跨平台安全删除工具": "DelGuard - Plattformsoberoende Säker Borttagningsverktyg"
  "用法:": "Användning:"
  "选项:": "Alternativ:"
  "文件:": "Fil:"
  "目录:": "Katalog:"
  "版本": "Version"
  "帮助": "Hjälp"

deletion_operations:
  "删除 %s ? [y/N/a/q]: ": "Ta bort %s ? [y/N/a/q]: "
  "已跳过 %s\n": "Hoppade över %s\n"
  "检测到关键路径，要求双重确认：%s\n": "Kritisk sökväg upptäckt, dubbel bekräftelse krävs: %s\n"
  "已取消关键路径 %s 的删除\n": "Borttagning av kritisk sökväg %s avbruten\n"
  "[DRY-RUN] 将把 %s 移动到回收站\n": "[TORRKÖRNING] Skulle flytta %s till papperskorg\n"
  "错误：无法删除 %s: %v\n": "Fel: kan inte ta bort %s: %v\n"
  "已将 %s 移动到回收站\n": "Flyttade %s till papperskorg\n"

system_warnings:
  "警告：当前以高权限运行（root/管理员），已强制启用交互确认。\n": "Varning: kör med förhöjda privilegier (root/Administratör). Interaktiv bekräftelse tvingad.\n"
  "当前平台 %s 暂不支持回收站功能\n": "Nuvarande plattform %s stöder inte papperskorgsfunktionalitet\n"
  "警告：即将删除关键路径: %s\n": "Varning: på väg att ta bort kritisk sökväg: %s\n"
  "为确认风险，请输入完整路径继续（或直接回车取消）：": "För att bekräfta risk, ange fullständig sökväg för att fortsätta (eller tryck Enter för att avbryta): "
  "警告：当前以管理员/root权限运行，即将删除: %s\n": "Varning: kör som administratör/root, på väg att ta bort: %s\n"
  "确认删除？[y/N]: ": "Bekräfta borttagning? [y/N]: "

file_status:
  "警告：文件 %s 为只读文件\n": "Varning: fil %s är skrivskyddad\n"
  "确认删除只读文件？[y/N]: ": "Bekräfta borttagning av skrivskyddad fil? [y/N]: "
  "警告：检测到回收站/废纸篓目录: %s\n": "Varning: papperskorg/papperskorgskatalog upptäckt: %s\n"
  "确认删除回收站目录？[y/N]: ": "Bekräfta borttagning av papperskorgskatalog? [y/N]: "
  "警告：检测到DelGuard程序目录: %s\n": "Varning: DelGuard programkatalog upptäckt: %s\n"
  "确认删除程序目录？[y/N]: ": "Bekräfta borttagning av programkatalog? [y/N]: "

error_messages:
  "错误：权限不足，无法删除 %s\n": "Fel: otillräckliga behörigheter för att ta bort %s\n"
  "错误：系统保护文件，无法删除 %s\n": "Fel: systemskyddad fil, kan inte ta bort %s\n"
  "错误：路径包含非法字符: %s\n": "Fel: sökväg innehåller ogiltiga tecken: %s\n"
  "错误：路径过长: %s\n": "Fel: sökväg för lång: %s\n"
  "错误：磁盘空间不足，无法删除 %s\n": "Fel: otillräckligt diskutrymme för att ta bort %s\n"
  "错误：文件正在被使用: %s\n": "Fel: fil används: %s\n"
  "错误：网络路径不可访问: %s\n": "Fel: nätverkssökväg inte tillgänglig: %s\n"
  "错误：符号链接目标不存在: %s\n": "Fel: symbolisk länkmål existerar inte: %s\n"
  "错误：文件系统只读: %s\n": "Fel: filsystem är skrivskyddat: %s\n"
  "错误：磁盘错误: %s\n": "Fel: diskfel: %s\n"
  "错误：内存不足: %s\n": "Fel: otillräckligt minne: %s\n"

smart_search:
  "未找到文件 '%s'，但发现以下相似文件：": "Fil '%s' hittades inte, men liknande filer hittades:"
  "请选择文件编号": "Välj filnummer"
  "取消操作": "Avbryt operation"
  "选择了文件": "Fil vald"
  "相似度": "Likhet"
  "匹配方式": "Matchningstyp"
  "内容匹配": "Innehållsmatchning"

user_interface:
  "确认": "Bekräfta"
  "取消": "Avbryt"
  "跳过": "Hoppa över"
  "全部": "Alla"
  "退出": "Avsluta"
  "继续": "Fortsätt"
  "重试": "Försök igen"
  "忽略": "Ignorera"

progress_stats:
  "删除进度": "Borttagningsframsteg"
  "完成": "Slutförd"
  "失败": "Misslyckades"
  "成功": "Lyckades"
  "总计": "Totalt"
  "处理中": "Bearbetar"
  "已完成": "Färdig"

configuration:
  "配置": "Konfiguration"
  "设置": "Inställningar"
  "语言": "Språk"
  "主题": "Tema"
  "日志": "Logg"
  "备份": "Säkerhetskopiering"
  "安全": "Säkerhet"
  "性能": "Prestanda"

help_info:
  "使用帮助": "Användningshjälp"
  "命令说明": "Kommandobeskrivning"
  "参数列表": "Parameterlista"
  "示例": "Exempel"
  "注意事项": "Viktiga punkter"
  "常见问题": "Vanliga frågor"

file_types:
  "文件": "Fil"
  "目录": "Katalog"
  "符号链接": "Symbolisk länk"
  "隐藏文件": "Dold fil"
  "系统文件": "Systemfil"
  "只读文件": "Skrivskyddad fil"
  "可执行文件": "Körbar fil"

operation_results:
  "操作成功": "Operation lyckades"
  "操作失败": "Operation misslyckades"
  "操作取消": "Operation avbruten"
  "操作超时": "Operation timeout"
  "操作完成": "Operation slutförd"
  "操作中断": "Operation avbruten"

special_features:
  "智能搜索": "Intelligent sökning"
  "自动备份": "Automatisk säkerhetskopiering"
  "安全删除": "Säker borttagning"
  "批量处理": "Batchbearbetning"
  "并行处理": "Parallell bearbetning"
  "增量备份": "Inkrementell säkerhetskopiering"

# 扩展配置段
advanced_features:
  "高级配置": "Avancerad konfiguration"
  "性能优化": "Prestandaoptimering"
  "安全增强": "Säkerhetsförstärkning"
  "用户体验": "Användarupplevelse"
  "自定义选项": "Anpassade alternativ"
  "扩展功能": "Utökade funktioner"

# 新增特性
new_features:
  "并行处理支持": "Parallell bearbetningsstöd"
  "智能备份策略": "Intelligent säkerhetskopieringsstrategi"
  "高级过滤器": "Avancerade filter"
  "用户钩子系统": "Användaranpassat hooksystem"
  "配置文件格式": "Konfigurationsfilformat"
  "多语言支持": "Flerspråksstöd"
